Algoritmo "semnome"
//Faça um algoritmo para calcular a área de uma circunferência, considerando a
//fórmula ÁREA = p * RAIO². Utilize as variáveis AREA e RAIO, a constante p (pi =
//3,14159) e os operadores aritméticos de multiplicação

Var
area,raio: real
pii: real

Inicio

pii<-3.14

escreval ("escreva o valor do raio : ")
leia (raio)

area<- (raio*raio) *pii

escreval("O valor da área é de :", area)



Fimalgoritmo